name: Bug report
description: Create a report to help us improve
title: "[BUG] Description"
labels: bug
body:
- type: textarea
  attributes:
    label: Describe the bug
    description: A clear and concise description of the bug.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. Go to ...
      2. Click on ...
      3. Scroll to ...
      4. See error ...
  validations:
    required: true
- type: textarea
  attributes:
    label: Debug log
    description: |
      If the bug relates to an error you must provide your FULL kodi.log file
      Either upload your log to https://paste.kodi.tv/ and provide the link OR attach the log file here.
      
      Tip: You can attach files by clicking this area to highlight it and then dragging files in.
      https://kodi.wiki/view/Log_file#Log_file_location
  validations:
    required: false
- type: textarea
  attributes:
    label: Screenshots and Additional Info
    description: |
      Provide any relevant additional information such as screenshots or other details here.

      Tip: You can attach images by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
- type: checkboxes
  attributes:
    label: Checklist
    description: Before submitting your bug report.
    options:
    - label: I have searched the issues and this bug has not been reported.
      required: true
    - label: I have updated TMDbHelper to the most recent version.
      required: true
    - label: I have described the bug and included steps to reproduce the issue
      required: true
    - label: I have uploaded my debug log.
      required: false