name: Feature request
description: Suggest an idea for this project
title: "[Feature] Description"
labels: enhancement
body:
- type: textarea
  attributes:
    label: Describe the feature that you'd like
    description: A clear and concise description of what you want to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Why is this feature needed? What problem does it solve?
    description: A clear explanation justifying why this feature should be added Ex. I'm always frustrated when [...].
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps to reproduce.
    description: If this feature relates to an existing problem, please describe the steps to reproduce the issue.
    placeholder: |
      1. Go to ...
      2. Click on ...
      3. Scroll to ...
      4. See issue ...
  validations:
    required: false
- type: textarea
  attributes:
    label: Screenshots and Additional Info
    description: |
      Provide any relevant additional information such as screenshots, log files, or other details here.

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
- type: checkboxes
  attributes:
    label: Checklist
    description: Before submitting your feature request.
    options:
    - label: I have searched the issues and this feature has not been requested.
      required: true
    - label: I have updated TMDbHelper to the most recent version.
      required: true